version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    container_name: bookshop-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword123
    ports:
      - "1436:1433"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "P@ssword123", "-Q", "SELECT 1" ]
      interval: 10s
      retries: 5
